--ataque (id, nombre, porc_dano, porc_precision, tiempo)
insert into Ataque values(1, 'Golpe', 1, 100, 1000);
insert into Ataque values(2, 'Tajo', 50, 100, 500);
insert into Ataque values(3, 'Navajazo', 75, 75, 800);
insert into Ataque values(4, 'Lanzamiento', 100, 50, 1000);
insert into Ataque values(5, 'Vertical', 50, 100, 500);
insert into Ataque values(6, 'Estocada', 75, 75, 800);
insert into Ataque values(7, 'Circular', 100, 50, 1200);
insert into Ataque values(8, 'Oblicuo', 50, 100, 700);
insert into Ataque values(9, 'Sesgada', 75, 75, 1000);
insert into Ataque values(10, 'Martillo de Helm', 100, 50, 1500);


-- id, defensa, fuerza, nivel, nombre, precio, precision, tipo, velocidad, vida
insert into Item values(1, 20, 15, 1, 'Botas de montar', 50, 0, 4, 30, 50,null,null,null);
insert into Item values(2, 0, 30, 1, 'Daga de caza', 50, 20, 1, 15, 0, 2, 3, 4);
insert into Item values(3, 30, 5, 1, 'Escudo del dragon', 80, 5, 3, 5, 70, null,null,null);
insert into Item values(4, 0, 50, 1, 'Espada matadragones', 80, 10, 1, 5, 0, 5, 6, 7);
insert into Item values(5, 0, 70, 1, 'Gran mandoble', 150, 5, 1, -5, 0, 8, 9, 10);
insert into Item values(6, 20, 0, 1, 'Yelmo de cuero', 50, 5, 0, 10, 50,null,null,null);
insert into Item values(7, 100, 0, 1, 'Placas de gladiador', 50, 0, 2, 0, 120,null,null,null);
insert into Item values(8, 200, 0, 2, 'Armadura pesada', 100, 0, 2, -20, 150,null,null,null);

insert into Bestia values(1, 5, 10, 20,1, 'Murcielago', 10, 50, 50, 100, 50,1,1);
insert into Bestia values(2, 50, 20, 50, 3, 'Escorpion', 30, 10, 75, 90, 80,1, 2);
insert into Bestia values(3, 70, 30, 75, 5, 'Tentaculo', 60, 10, 77, 105, 110,1,3);
insert into Bestia values(4, 110, 40, 100, 7, 'Ent', 80, 10, 75, 110, 150,1,4);
insert into Bestia values(5, 100, 50, 120, 9, 'Troll', 100, 10, 80, 140, 190,1,5);
insert into Bestia values(6, 140, 75, 140, 11, 'Ogro', 150, 10, 82, 150, 230,1,6);
insert into Bestia values(7, 200, 100, 250, 13, 'Grifo', 200, 10, 78, 140, 300,1,7);
insert into Bestia values(8, 200, 130, 200, 15, 'Serpiente marina', 260, 10, 83, 160, 340,1,8);
insert into Bestia values(9, 400, 200, 300, 17, 'Dragonido armero', 400, 10, 76, 180, 450,1,8);
insert into Bestia values(10, 500, 250, 400, 19, 'Dragonido ama de casa', 500, 10, 80, 190, 600,1,8);
insert into Bestia values(11, 650, 400, 600, 21, 'Dragonido quemador', 800, 10, 90, 235, 800, 1,8);
insert into Bestia values(12, 900, 750, 900, 23, 'Gran dragon rojo', 1500, 10, 95, 245, 950, 1,8);


--create table heroe (id, defensa, expSiguienteNivel fuerza , imagen , nivel , nombre, oro , precision , puntos_hab , velocidad , vida , xp , armadura , botas , casco, escudo ,espada , primary key (id))
--create table heroe_inventario (heroe bigint not null, inventario bigint not null)
--create table item (id, defensa, fuerza, nivel, nombre varchar(255), precio, precision, tipo, velocidad, vida, at1, at2, at3
--create table bestia (id bigint generated by default as identity (start with 1), defensa integer not null, exp integer not null, fuerza integer not null, imagen varchar(255), nivel integer not null, nombre varchar(255), oro integer not null, precision integer not null, velocidad integer not null, vida integer not null, primary key (id))
insert into Heroe values (1,10,100,10,'resources/combates/fotos/aethyr-second.png',1,'user',50,30,10,5,100,0,null,null,null,null,null);
insert into Heroe values (2,10,100,10,'resources/combates/fotos/cloaked.png',1,'user2',50,30,10,5,100,0,null,null,null,null,null);
insert into Heroe values (3,10,100,10,'resources/combates/fotos/jetto.png',1,'user3',50,30,10,5,100,0,null,null,null,null,null);
insert into Heroe values (4,10,100,10,'resources/combates/fotos/karrag.png',1,'user4',50,30,10,5,100,0,null,null,null,null,null);
insert into Heroe values (5,10,100,10,'resources/combates/fotos/aethyr-second.png',1,'user5',50,30,10,5,100,0,null,null,null,null,null);
insert into Heroe values (6,10,100,10,'resources/combates/fotos/jetto.png',1,'user6',50,30,10,5,100,0,null,null,null,null,null);
insert into Heroe values (7,10,100,10,'resources/combates/fotos/karrag.png',1,'user7',50,30,10,5,100,0,null,null,null,null,null);
insert into Heroe values (8,10,100,10,'resources/combates/fotos/cloaked.png',1,'user8',50,30,10,5,100,0,null,null,null,null,null);
insert into Heroe values (9,10,100,10,'resources/combates/fotos/jetto.png',1,'user9',50,30,10,5,100,0,null,null,null,null,null);
insert into Heroe values (10,10,100,10,'resources/combates/fotos/aethyr-second.png',1,'user10',50,30,10,5,100,0,null,null,null,null,null);
insert into Heroe values (11,10,100,10,'resources/combates/fotos/cloaked.png',1,'user11',50,30,10,5,100,0,null,null,null,null,null);

insert into User values (1,false, '$2a$10$E44pf9xwD4CFda8FtvrWGeX1Axj2RnC49AK/vjttAWARoyGfrSGPm', 'user', 'user',1);
insert into User values (2,false, '$2a$10$EhYtXcHYOMXXUWAyiOfKIO21uxLRf4dNDdXZL73NLfMVQqiFdZncW', 'admin', 'admin',null);
insert into User values (3, false, '$2a$10$sj7CegQYfvKqcuxKoVbis.rId1sdR/qpfNOua63XFUTlTOnLXazLO', 'adminw', 'admin', null);
insert into User values (4, false, '$2a$10$Vt9RrxPqdyPDRRLMfyZnzOv6nFIPMzmiKgFSF90vCaABgmm75O29C', 'jasandov@ucm.es', 'admin', null);
insert into User values (5,false, '$2a$10$FrBpGZldacxMbYsaPansR.hRgSdCcb.RWBX7AD.5wpzN1TxnAE/Ry', 'user2', 'user',2);
insert into User values (6,false, '$2a$10$/GDiS8KzypGKuYEvq97yg.sMfeSd/q/eNavk707o96bV.DLm6a3ma', 'user3', 'user',3);
insert into User values (7,false, '$2a$10$xCxqamC7hay9Eo.nF/Re7OawzNyVBkahTidSPHIMjyuP.yT0HoPpu', 'user4', 'user',4);
insert into User values (8,false, '$2a$10$xmnRq8aB2KJ4ZeUumuSWYehg/N6uNjjiQzX65aie7aliIyhD3mZai', 'user5', 'user',5);
insert into User values (9,false, '$2a$10$UlYDvh3B8F9gYvf21c3I5uPUO9b0c57ElOFbrmFqGb105eTzFltLe', 'user6', 'user',6);
insert into User values (10,false, '$2a$10$mu8/2lS9Gjzwx4MdSUMpUOYWddp01lOL/6PUDHZIKGyG82eqVzB9u', 'user7', 'user',7);
insert into User values (11,false, '$2a$10$B2LGIt0DUgTCpZMmIvxzYeBLmg83y8bpnZ.vOTakLd.SZVeZKoGDi', 'user8', 'user',8);
insert into User values (12,false, '$2a$10$PaQ0./7xBSC9f2kt9kKscup1UsXLX3NJVnqM71aVzvrvUXpfdyzE6', 'user9', 'user',9);